name: qrserv
description: Transfer files with ease over a network.

publish_to: 'none'

version: 2.7.6+56

environment:
    sdk: '>= 3.10.0 <4.0.0'
    flutter: ^3.38.1

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.20.2

    path_provider: ^2.1.5
    filesize: ^2.0.1
    qr_flutter: ^4.1.0
    watcher: ^1.2.0
    package_info_plus: ^9.0.0
    url_launcher: ^6.3.2
    oktoast: ^3.4.0
    share_plus: ^12.0.1
    share_handler: ^0.0.25

    file_picker: ^10.3.8
    flutter_archive: ^6.0.4

    window_size:
        git:
            url: https://github.com/google/flutter-desktop-embedding.git
            path: plugins/window_size
            ref: a738913c8ce2c9f47515382d40827e794a334274

    http: ^1.5.0
    uuid: ^4.5.1
    ffi: ^2.1.4
    win32: ^5.15.0

    filesystem_picker: ^4.1.0
    permission_handler: ^12.0.1
    device_info_plus: ^12.2.0
    path: ^1.9.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter

flutter:
    uses-material-design: true
    generate: true
    fonts:
        - family: Nunito
          fonts:
              - asset: fonts/Nunito-Variable.ttf
